#!/usr/bin/env python3
"""Nickelodeon.
A novelty-piano roll, the sound of a coin-fed player piano: the
Confrey-era idiom written for a perforated roll rather than for hands.
It does what hands can't quite, and does it without tiring, nonstop
sixteenth-note figuration in the right hand with the "secondary rag"
3+3+2 cross-accent, octave punctuations, a whole-tone flourish, and a
dead-steady tempo, over a mechanical oom-pah bass.

Because the figuration is regular, the right hand is generated by a
helper rather than typed out, which is also a small demonstration of
building a score programmatically and handing scoremill the notes.
humanize is off on purpose: a roll does not rush or drag.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scoremill import Song

# Right-hand figuration lives at c5 and above; the left hand tops out
# below it, so the roll never punches two hammers at one key.
ARP = {
    "C":   ["c5", "e5", "g5", "c6", "e6", "c6", "g5", "e5"],
    "G7":  ["d5", "f5", "g5", "b5", "d6", "b5", "g5", "f5"],
    "F":   ["c5", "f5", "a5", "c6", "f6", "c6", "a5", "f5"],
    "D7":  ["d5", "f#5", "a5", "d6", "f#6", "d6", "a5", "f#5"],
    "C7":  ["e5", "g5", "bb5", "c6", "e6", "c6", "bb5", "g5"],
    "Am":  ["c5", "e5", "a5", "c6", "e6", "c6", "a5", "e5"],
    "Bb":  ["d5", "f5", "bb5", "d6", "f6", "d6", "bb5", "f5"],
}


def run(chord):
    """One bar of eight-sixteenth figuration with 3+3+2 accents."""
    ps = ARP[chord]
    return " ".join(f"{p}s>" if i in (0, 3, 6) else f"{p}s"
                    for i, p in enumerate(ps))


def fig_line(plan):
    """A strain from a plan of (chord, 'fig') or ('oct-token', 'oct')."""
    bars = []
    for item, kind in plan:
        bars.append(run(item) if kind == "fig" else item)
    return " | ".join(bars) + " |"


VOICE = {
    "C":   ("c2", "[e3 g3 c4]", "g2"),
    "G7":  ("g2", "[d3 f3 b3]", "d3"),
    "F":   ("f2", "[a3 c4 f4]", "c3"),
    "D7":  ("d2", "[f#3 a3 c4]", "a2"),
    "C7":  ("c2", "[e3 g3 bb3]", "g2"),
    "Am":  ("a2", "[a3 c4 e4]", "e3"),
    "Bb":  ("bb1", "[d3 f3 bb3]", "f2"),
}


def oompah(chords):
    bars = []
    for c in chords:
        if isinstance(c, tuple):
            bars.append(" ".join(f"{VOICE[cc][0]}e {VOICE[cc][1]}e"
                                 for cc in c))
        else:
            b1, ch, b2 = VOICE[c]
            bars.append(f"{b1}e {ch}e {b2}e {ch}e")
    return " | ".join(bars) + " |"


s = Song(tempo=108, time="2/4", key="C", humanize=0, expressive=True)

# ── INTRO (4 bars): a cascade and a mechanical stamp ──
I = s.section("Intro")
I.voice("rh", vel=60).bars(
    "!f " + run("C") + " | " + run("G7") + " |"
    " [c6 e6]s [g5 c6]s [e5 g5]s [c5 e5]s"
    " [c6 e6]s [g5 c6]s [e5 g5]s [c5 e5]s |"
    " [g5 g6]e [f5 f6]e [d5 d6]e [f5 f6]e |")
I.voice("lh", vel=52).bars(oompah(["C", "G7", "C", "G7"]))

# ── A STRAIN (16 bars): perpetual motion over a rag progression ──
A_PLAN = [
    ("C", "fig"), ("C", "fig"), ("G7", "fig"),
    ("[g5 g6]e [e5 e6]e [c5 c6]q", "oct"),
    ("C", "fig"), ("C", "fig"), ("G7", "fig"),
    ("[e5 e6]e [g5 g6]e [c6 c7]q", "oct"),
    ("F", "fig"), ("D7", "fig"), ("G7", "fig"),
    ("[d5 d6]e [f5 f6]e [g5 g6]q", "oct"),
    ("C", "fig"), ("Am", "fig"), ("G7", "fig"),
    ("[e5 e6]e [d5 d6]e [c5 c6]q", "oct"),
]
A = s.section("A")
A.voice("rh", vel=62).bars("!mf " + fig_line(A_PLAN))
A.voice("lh", vel=50).bars(oompah(
    ["C", "C", "G7", "C", "C", "C", "G7", "C",
     "F", "D7", "G7", "C", "C", "Am", "G7", "C"]))

# ── B STRAIN (16 bars): repeated dyads and a whole-tone flourish ──
DYAD_C = ("[c6 e6]s [c6 e6]s [b5 d6]s [b5 d6]s"
          " [c6 e6]s [c6 e6]s [g5 c6]s [g5 c6]s")
DYAD_F = ("[c6 f6]s [c6 f6]s [a5 c6]s [a5 c6]s"
          " [c6 f6]s [c6 f6]s [f5 a5]s [f5 a5]s")
DOWN_C = ("[e6 g6]s [c6 e6]s [g5 c6]s [e5 g5]s"
          " [c6 e6]s [g5 c6]s [e5 g5]s [c5 e5]s")
UP_G7 = ("[d6 f6]s [b5 d6]s [g5 b5]s [d5 g5]s"
         " [g5 b5]s [d6 f6]s [g6 b6]s [d6 f6]s")
DOWN_F = ("[f6 a6]s [c6 f6]s [a5 c6]s [f5 a5]s"
          " [c6 f6]s [a5 c6]s [f5 a5]s [c5 f5]s")
DOWN_G7 = ("[d6 f6]s [b5 d6]s [g5 b5]s [d5 g5]s"
           " [b5 d6]s [g5 b5]s [d5 g5]s [g5 b5]s")
WHOLE = "c5s> d5s e5s f#5s> g#5s a#5s c6s> d6s"     # whole-tone run up
WHOLE2 = "d6s> c6s a#5s g#5s> f#5s e5s d5s> c5s"    # and back down
B_BARS = [
    "!f " + DYAD_C, DOWN_C, DYAD_C, UP_G7,           # 1-4
    WHOLE, WHOLE2,                                     # 5-6
    "[c6 e6]s [e6 g6]s [g6 c7]s [e6 g6]s"
    " [c6 e6]s [g5 c6]s [e5 g5]s [c5 e5]s",           # 7
    "[g5 g6]e [e5 e6]e [c5 c6]q",                      # 8  cadence
    DYAD_F, DOWN_F, WHOLE, WHOLE2,                    # 9-12
    DOWN_G7, DYAD_C, DOWN_G7,                          # 13-15
    "[e5 e6]e [d5 d6]e [c5 c6]q",                      # 16 cadence
]
B = s.section("B")
B.voice("rh", vel=64).bars(" | ".join(B_BARS) + " |")
B.voice("lh", vel=52).bars(oompah(
    ["C", "C", "C", "G7", "C", "C", "C", "C",
     "F", "F", "C", "G7", "G7", "C", "G7", "C"]))

# ── TRIO (16 bars): the sweet strain in F, filigree with a tune on top ──
T_PLAN = [
    ("F", "fig"), ("F", "fig"), ("C7", "fig"),
    ("[a5 a6]e [g5 g6]e [f5 f6]q", "oct"),
    ("F", "fig"), ("F", "fig"), ("C7", "fig"),
    ("[c6 c7]e [a5 a6]e [f5 f6]q", "oct"),
    ("Bb", "fig"), ("F", "fig"), ("C7", "fig"),
    ("[g5 g6]e [bb5 bb6]e [a5 a6]q", "oct"),
    ("F", "fig"), ("D7", "fig"), ("C7", "fig"),
    ("[c6 c7]e [a5 a6]e [f5 f6]q", "oct"),
]
T = s.section("Trio", key="F")
T.voice("rh", vel=58).bars("!mf " + fig_line(T_PLAN))
T.voice("lh", vel=48).bars(oompah(
    ["F", "F", "C7", "F", "F", "F", "C7", "F",
     "Bb", "F", "C7", "F", "F", "D7", "C7", "F"]))

s.arrange("Intro A A B Trio Trio")

s.describe()
s.lint(mode="homophonic")
rep = s.report()
print(f"duration {rep['duration_s']}s, "
      f"collisions {len(s.lint(quiet=True, mode='homophonic'))}")
out = s.save(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "nickelodeon.mid"))
print("wrote", out)
if "--play" in sys.argv:
    s.play()
